config/routes.rb
Rails.application.routes.draw do

#Nested resources
  root "artists#index"

    resources :artists, only: [:index, :show, :destroy] do
    resources :songs, only: [:new, :destroy, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs, dependent: :destroy

  validates :artist_name, presence: true
  validates :artist_name, uniqueness: true
  validates :image_url, presence: false
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist

  validates :song_name, presence: true
  validates :artist, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, except: [:index]
  before_action :set_songs, except: [:index]

  #assigns all artists in db to an instance variable
  def index
    @artists = Artist.all
  end

  def show
    @artist = Artist.find(params[:id])
    @songs = @artist.songs
    @songs = Song.new
  end



  def destroy
    if @artist.destroy
    redirect_to artists_path, notice: "Artist and their songs have been deleted"

    else
      redirect_to artists_path
    end
  end

#selects artist that song belongs to
  private

  def set_artist
    @artist = Artist.find(params[:id])
  end

  def set_songs
    @songs = Artist.find(params[:id])
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  before_action :set_artist

  def new
    @song = Song.new
  end

  def create
    @song = @artist.songs.create(song_params)

    if @song.save
    redirect_to artist_path(@artist), notice: "Thanks for adding a new song!"
    else
      render :new
    end
  end

  def destroy
    @song = Song.find(params[:id])
    @song.destroy
    redirect_to artist_path(@artist.id), notice: "You've deleted this song"
  end


  private

  def song_params
      params.require(:song).permit(:song_name, :artist_id)
  end

  def set_artist
    @artist = Artist.find(params[:artist_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/index.html.erb
<div class="jumbotron">
      <div class="container">
        <h1> Welcome to Bamboo Quacking! </h1>
        <p>What is Bamboo Quacking, you might ask? It's the coolest, newest place to create events and meet people who are bamboo-quacking-minded :) </p>
        <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
      </div>
    </div>

    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
       </div>
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
      </div>

      <hr>

      <footer>
        <p>&copy; 2016 Company, Inc.</p>
      </footer>
    </div> <!-- /container -->


      <h1 class>Artists</h1>

      <% @artists.each do |artist| %>
        <p><%= link_to artist.artist_name, artist_path(artist.id) %></p>
      <% end %>

app/views/artists/show.html.erb
<h1><%= @artist.artist_name %></h1>

<%= image_tag @artist.image_url %>

<h2> List of Songs by <%= @artist.artist_name %></h2>

<% if @artist.songs.any? %>
  <ul>
    <% @artist.songs.each do |song| %>
      <p><%= song.song_name %>
      <%= link_to "Delete Song", artist_song_path(@artist.id, song.id), method: :delete, data: {confirm: "Are you sure you want to delete this song?"} %></p>
      <% end %>
  </ul>
<% else %>
  <p>There are no songs in this artist.</p>
<% end %>
<hr>

<%= link_to "Click to add new song", new_artist_song_path(@artist.id) %>

<hr>

<%= link_to "Click to delete artist", artist_path(@artist.id),  method: :delete, data:{confirm:"Are you sure you want to delete this artist and all their songs?"} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codaisseurify</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

    <br><br>
    <hr>
    <%= link_to "[All Artists]", root_path %>
  </body>
</html>

app/views/songs/new.html.erb
<%= form_for [@artist, @song] do |f| %>

  <%= f.label :name %>
  <%= f.text_field :song_name, placeholder: "Add new song name" %>

  <%= f.submit "Save" %>

<% end %>